project:
  type: website
  output-dir: docs

website:
  title: "VT Club Tennis Analysis"
  navbar:
    left:
      - href: main.qmd
        text: Home
      - text: "Financial Analysis"
        menu:
          - href: financial_analysis.qmd
            text: "Overview"
          - href: historical_review.qmd
            text: "Historical Review"
          - href: financial_tools.qmd
            text: "Budget Tool"
      - href: performance_analysis.qmd
        text: "Performance Analysis"

format:
  html:
    theme: cosmo
    css: chat-widget.css
    include-after-body: chat-widget.html
    toc: true
