project:
  type: website
  output-dir: docs

website:
  title: "VT Club Tennis Analysis"
  navbar:
    left:
      - href: main.qmd
        text: Home
      - href: about.qmd
        text: "About Us"
      - href: project_log.qmd
        text: "Project Log"
      - text: "Financial Analysis"
        menu:
          - href: financial_analysis.qmd
            text: "Overview"
          - href: historical_review.qmd
            text: "Historical Review"
          - href: financial_tools.qmd
            text: "Budget Tool"
      - text: "Performance Analysis"
        menu:
          - href: performance_analysis.qmd
            text: "Overview"
          - href: rank_ladder.qmd
            text: "Ranking System"

format:
  html:
    theme: cosmo
    css: 
      - chat-widget.css
      - styles.css
    include-after-body: chat-widget.html
    toc: true
